GET http://localhost:5000

### register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email" : "your2truly34@gmail.com",
    "password" : "123456"
}

### login route
POST  http://localhost:5000/auth/login
Content-Type: application/json

{
    "email" : "your2truly34@gmail.com",
    "password" : "123456"
}


### refresh token route
POST  http://localhost:5000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjM3NTM4OTMsImV4cCI6MTY5NTMxMTQ5MywiYXVkIjoiMSIsImlzcyI6InBpY2t1cnBhZ2UuY29tIn0.mINmhoev-mi_MCkL4PclE1vLnTV3nmR1ziD-aArIUAY"
}    

### logout route
DELETE   http://localhost:5000/auth/logout
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjM3NTQ3OTksImV4cCI6MTY5NTMxMjM5OSwiYXVkIjoiMiIsImlzcyI6InBpY2t1cnBhZ2UuY29tIn0.tR6PGl8NPtob78fBCVv7m8bRzV3XKgmeidzbCnP5z6s"

}    